# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Homelab
repo_url: https://github.com/khuedoan/homelab

theme:
  name: material
  palette:
    primary: black

markdown_extensions:
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
