users:
  - name: gitea_admin
    fullName: Admin
    email: admin@khuedoan.com
    accessTokens:
      - renovate
    oauthApplications:
      - name: dex
        redirectUrl: https://dex.khuedoan.com/callback
organizations:
  - name: ops
    description: Operations
    teams:
      - name: Owners
        members:
          - renovate
repositories:
  - name: homelab
    owner: ops
    private: false
    migrate:
      source: https://github.com/khuedoan/homelab
      mirror: false
    # TODO create webhook (use a global one?)
    # webhooks:
    #   - http://gitea-webhook.tekton-pipelines:3000
  - name: blog
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/blog
      mirror: true
  - name: backstage
    owner: khuedoan
    migrate:
      source: https://github.com/khuedoan/backstage
      mirror: true
