metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.40.110, mac: '8e:84:46:72:d4:62', disk: sda, network_interface: ens18}
    workers:
      hosts:
        metal1: {ansible_host: 192.168.40.111, mac: 'd2:77:1e:5f:9f:3b', disk: sda, network_interface: ens18}
